import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"], // අවශ්‍ය මහත ප්‍රමාණයන්
  variable: "--font-jakarta", // CSS Variable එකක් ලෙස පාවිච්චි කිරීමට
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";
import Navbar from "@/components/section/navBar";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <Navbar />

        <main>{children}</main>
      </body>
    </html>
  );
}
